### PR TITLE
Test

### PR DESCRIPTION
**Pull request by ElijahLynn**

### CODE REVIEW

**Comment by mbenziane** [comment]
Created an environment devops-vagovcms#pr-30<br><br> [button_visit-site](http://prdevops-30.va.agile6.com)

**Comment by ElijahLynn** [comment]
Tested stack destroy on close, works!

**Comment by ElijahLynn** [comment]
Testing a re-open

**Comment by mbenziane** [comment]
Created an environment devops-vagovcms#pr-30<br><br> [button_visit-site](http://prdevops-30.va.agile6.com)

**Pull request closed without merging**
